name: IPLTrackX Auto-Bot

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - name: Create Auth Files
        env:
          TOKEN_DATA: ${{ secrets.TOKEN_JSON }}
          CRED_DATA: ${{ secrets.CREDENTIALS_JSON }}
        run: |
          import os
          if os.environ.get("TOKEN_DATA"):
              open("token.json","w").write(os.environ["TOKEN_DATA"])
          if os.environ.get("CRED_DATA"):
              open("credentials.json","w").write(os.environ["CRED_DATA"])
        shell: python

      - name: Run Pipeline
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        run: python control/main.py

      - name: Save History
        run: |
          git config --global user.name "IPLBot"
          git config --global user.email "bot@ipltrackx.com"
          git add data/history.txt || true
          git commit -m "Update History [skip ci]" || echo "No change"
          git push || echo "Nothing to push"

